### ISSUE TITLE
sync-content export taxonomy error

### ISSUE THREAD

**Issue by petrji** [kontent-ai/kontent-ai-migration-toolkit#5]
### Brief bug description

When running **sync-content export** we are getting mapping error. The error happens only for some taxonomies. We couldn't identify the pattern. The error message below. 

Error: Failed to map value of element 'taxonomy_codename' of type 'taxonomy'. Value: [{"id":"5b481c9d-8c4d-4a56-bfe6-f84c2b96a736"}]. Message: Cannot read properties of undefined (reading 'id')
at getValueToStoreFromElement (file:///C:/Users/myusername/AppData/Local/npm-cache/_npx/05fa19e8fffd21ea/node_modules/@kontent-ai/migration-toolkit/dist/es2022/export/export-manager.js:96:19)
at file:///C:/Users/myusername/AppData/Local/npm-cache/_npx/05fa19e8fffd21ea/node_modules/@kontent-ai/migration-toolkit/dist/es2022/export/export-manager.js:65:24
at Array.reduce (<anonymous>)
at getMigrationElements (file:///C:/Users/myusername/AppData/Local/npm-cache/_npx/05fa19e8fffd21ea/node_modules/@kontent-ai/migration-toolkit/dist/es2022/export/export-manager.js:61:14)
at file:///C:/Users/myusername/AppData/Local/npm-cache/_npx/05fa19e8fffd21ea/node_modules/@kontent-ai/migration-toolkit/dist/es2022/export/export-manager.js:25:31
at Array.map (<anonymous>)
at mapToMigrationItem (file:///C:/Users/myusername/AppData/Local/npm-cache/_npx/05fa19e8fffd21ea/node_modules/@kontent-ai/migration-toolkit/dist/es2022/export/export-manager.js:23:43)
at file:///C:/Users/myusername/AppData/Local/npm-cache/_npx/05fa19e8fffd21ea/node_modules/@kontent-ai/migration-toolkit/dist/es2022/export/export-manager.js:9:56
at Array.map (<anonymous>)
at getMigrationItems (file:///C:/Users/myusername/AppData/Local/npm-cache/_npx/05fa19e8fffd21ea/node_modules/@kontent-ai/migration-toolkit/dist/es2022/export/export-manager.js:9:36)

### Test environment

 - Platform/OS: Win10
 - Version1.3.0

**Comment by Enngage** [comment]
Hi @petrji , thank you for letting us know! There was indeed a problem with mapping of taxonomy elements. I've fixed that and released an update (v `1.4.0`), but you might need to wait a bit until this is merged do the `data-ops` unless you want to use this library directly.
